name: Build Static Page
on:
  push:
    branches:
      - feature/static-page
  pull_request:
    branches:
      - develop
jobs:
  build-page:
    name: Build Page
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: develop
      - name: Checkout Frontend
        run: cd frontend
      - name: Cache node modules
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Build and Deploy static Page
        shell: bash
        run: |
          npm run build
          sudo npm i -g @cloudbase/cli
          tcb login --apiKeyId ${{ secrets.SECRET_ID }} --apiKey ${{ secrets.SECRET_KEY }}
          tcb hosting deploy dist -e ${{ secrets.ENV_ID }} -r ap-guangzhou
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          