name: Build Static Page
on:
  push:
    branches:
      - bugfix/static-page
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build-page:
    name: Build Page
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache node modules
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Build static Page
        shell: bash
        run: |
          npm run build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_ID: ${{ github.run_id }}
      - name: GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
